config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#top"
  resources :posts, only: [:create, :destroy]
  resources :members, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create, :destroy]
  end
  resources :groups, only: [:index, :new, :edit, :update, :create, :destroy]
  resources :users, only: [:index, :edit, :show, :update] do
    collection do
      get 'search'
    end
  end

  namespace :following do
    resources :followeds, only: [:show] do
      resource :follow_requests, only:[:create, :destroy]
    end
  end
  
  namespace :followed do
    resources :followeds, only: [:show, :edit, :update] do
      resources :follow_okaies, only:[:index, :show, :destroy]
      post '/follow_requests/:id' => 'follow_requests#allow', as: 'allow'
      resources :follow_requests, only:[:index, :show, :destroy]
    end
  end
  get 'home/message'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :member
  belongs_to :user

  validates :message, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @user = current_user
    @members = @user.members.order('created_at DESC')
    @message = Message.new
    @messages = @member.messages.includes(:user)
  end

  def create
    @message = @member.messages.new(message_params)
    if @message.save
      redirect_to member_messages_path(@member), notice: 'メッセージが送信されました'
    else
      @messages = @member.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to  member_messages_path(@member.id)
  end

  private

  def message_params
    params.require(:message).permit(:message, :image).merge(user_id: current_user.id)
  end

  def set_group
    @member = Member.find(params[:member_id])
  end
end

app/views/messages/_main.html.erb
<div class="main">
  <div class="main-top">
    <div class="main-top__group">
      <h3 class="main-top__group"><%= @member.name %></h3>
    </div>
    <div class="main-top__member">
      <p class="main-top__member__text">Member :</p>
      <% @member.users.each do |user| %>
        <ul class="main-top__member__name">
          <li><%= user.name %></li>
        </ul>
      <% end %>
      <%= link_to  edit_member_path(@member) do%>
        <p>編集</p>
      <% end %>
    </div>
  </div>
  <div class="main-message">
    <% @messages.each do |message| %>
      <% if message.user.id == current_user.id %>
        <div class="main-message__box1">
          <div class="main-message__box1__info">
            <ul>             
              <li><%= message.user.name %></li>
              <li><%= image_tag "#{message.user.image}", class: "main-message__box1__info__image" %></li>
              <li ><%= message.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
            </ul>
          </div>
          <div class="main-message__box1__info__message">
            <% if message.message.present? %>
              <p><%= message.message %></p>
            <% end %>
            <% if  message.image.present? %>
            <%= image_tag "#{message.image}", class: "main-message__box1__image" %>
            <% end %>
          </div>
          <div class="main-message__box1__info__trash">
            <%= link_to member_message_path(@member.id, message.id), method: :delete do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="main-message__box2">
          <div class="main-message__box2__info">
            <ul>             
              <li><%= message.user.name %></li>
              <li><%= image_tag "#{message.user.image}", class: "main-message__box2__info__image" %></li>
              <li ><%= message.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
            </ul>
          </div>
          <div class="main-message__box2__info__message">
            <% if message.message.present? %>
              <p><%= message.message %></p>
            <% end %>
            <% if  message.image.present? %>
            <%= image_tag "#{message.image}", class: "main-message__box2__image" %>
            <% end %>
          </div>
          <div class="main-message__box2__info__trash">
            <%= link_to member_message_path(@member.id, message.id), method: :delete do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="main-bottom">
    <%= form_with model:  [@member, @message], html: {class: "message-form"}, local: true do |f| %>
      <div class ="form-box"> 
        <%= f.text_field :message, class: "form-box__message", placeholder: "type a message" %>
        <%= f.file_field :image,class: "form-part" %>
        <%# <i class="fas fa-image"></i> %>
        <%= f.submit class: "send" %>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side">
  <div class= "new-group">
    <%= link_to "Make Member", new_member_path, class:"make-member-btn" %>
  </div>
  <div class="member">
    <% @members.each do |member| %>
      <div class= "member-box">
        <%= link_to member_messages_path(member),class: "member-name" do %> 
          <%= member.name %> 
        <% end %>
        <div class ="member-list">
          <% member.users.each do |user| %>
            <ul>             
              <li><%= user.name %></li>
              <li><%= image_tag "#{user.image}", class: "member-image" %></li>
            </ul>
          <% end %>
        </div>
        <% if member.users.count > 5 %>
          <p class="member-count">他{<%= member.users.count-5 %>人}</p>
        <% end %>
        <p class="last-message"><%= member.show_last_message %>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<header>
    <div class="header-left">
      <% if @user.id == current_user.id %>
        <h1>Message*</h1>
      <% else %>
        <h1><%= @user.name %>'s page</h1>
      <% end %>
    </div>
    <div class="header-right">
      <ul class="header-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if @user.id == current_user.id %>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "マイページ", user_path(@user.id) %></li>
        <% else %>
          <li><%= link_to "クリエイター一覧", users_path %></li>
        <% end %>
      </ul> 
    </div>
</header>

<body>
  <div class="message-box">
    <%= render partial: 'side_bar' %>
    <%= render partial: 'main' %>
  </div>
</body>