config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#top"
  resources :posts, only: [:create, :destroy]
  resources :members, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create, :destroy]
  end
  resources :groups, only: [:index, :new, :edit, :update, :create, :destroy]
  resources :users, only: [:index, :edit, :show, :update] do
    collection do
      get 'search'
    end
  end

  namespace :following do
    resources :followeds, only: [:show] do
      resource :follow_requests, only:[:create, :destroy]
    end
  end
  
  namespace :followed do
    resources :followeds, only: [:show, :edit, :update] do
      resources :follow_okaies, only:[:index, :show, :destroy]
      post '/follow_requests/:id' => 'follow_requests#allow', as: 'allow'
      resources :follow_requests, only:[:index, :show, :destroy]
    end
  end
  get 'home/message'
end

app/models/group.rb
class Group < ApplicationRecord
# Relation
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :recruitments, dependent: :destroy
   	
  accepts_nested_attributes_for :recruitments, allow_destroy: true
# Validation
  validates :name, presence: true, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController  
  before_action :move_to_index, except: [:index]
  before_action :authenticate_user!, except: [:index]
  before_action :set_users, except: [:index]

  def index
    @q = Group.includes(:recruitments).order('created_at DESC').ransack(params[:q])
    @groups = @q.result(distinct: true)
    @count = @q.result.count
  end

  def new
    @group = Group.new
    @group.users << current_user
    @group.recruitments.new 
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice:"募集情報の投稿が完了しました。"
    else
      flash.now[:alert] = "募集情報の投稿に失敗しました。"
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if group_params[:recruitments_attributes].nil?
      render :edit
    end
    if @group.update(group_params)
      redirect_to root_path, notice:"募集情報が変更されました。"
    else
      render :edit
      flash.now[:alert] = "編集に失敗しました。"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to root_path, notice:"募集情報が削除されました。"
  end

  private
  
  def group_params
    params.require(:group).permit(:name, user_ids: [], recruitments_attributes: [:id, :title, :image, :adress, :description])
  end
  
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_users
    ids1 = current_user.following_okays.pluck(:followed_id) 
    ids2 = current_user.followed_okays.pluck(:following_id) 
    @users = User.where(id: ids1).or(User.where(id: ids2)).or(User.where(id: current_user))
  end

end

app/views/groups/_form.html.erb
<% if @group.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="recruit-new-area">
  <div class="recruit-new-box">
    <h2>募集情報を投稿する</h2> <br>
    <%= form_for @group do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "グループ名" ,class: "form-part1" %>
      </div>
      <div class="form-group">
        <%= f.collection_check_boxes :user_ids, @users, :id, :name %>
      </div>
      <%= f.fields_for :recruitments do |i| %>
        <%= i.label :"タイトル*" %><br />
        <%= i.text_field :title, class: "form-part2" %><br />
        <%= i.label :"イメージ*" %><br />
        <%= i.file_field :image,class: "form-part2" %><br />
        <%= i.label :"地域*" %><br />
        <%= i.select :adress, Recruitment.adresses.keys, {prompt: '選択してください'}, autofocus: true, autocomplete: "adress", class: "form-part2" %><br />
        <%= i.label :"説明文*" %><br />
        <%= i.text_area :description, class: "form-part3" %>
      <% end %>

      <div class="actions">
        <%= f.submit "投稿する",class: "form-part2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<%= render partial: 'form' %>

app/views/groups/index.html.erb
<header>
    <div class="header-left">
      <h1>Invitation*</h1>
    </div>
    <div class="header-right">
      <ul class="header-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in?%>
          <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
        <% end %>
      </ul> 
    </div>
</header>

<div class="invitation">
  <div class="side">
    <%= search_form_for @q do |f| %>  
      <div class="search-item">
        <%= f.label :name, "グループ名" %>
        <%= f.search_field :name_cont, class: "form-part" %>
      </div>
      <div class="search-item">
        <%= f.label :name, "ユーザー名" %>
        <%= f.search_field :users_name_cont, class: "form-part" %>
      </div>
      <div class="search-item">
        <%= f.label :title, "Keyword" %>
        <%= f.search_field :name_or_recruitments_title_or_recruitments_description_cont, class: "form-part1" %>
      </div>
      <div class="search-item">
        <%= f.label :adress, "Address:" %> 
        <%= f.select :recruitments_adress_eq, Recruitment.adresses.to_a.map{|k, v| [Recruitment.adresses_i18n[k], v]}, class: "form-part"  %>
      </div>
      <%= f.submit "検索", class: "sign-up" %>
    <% end %>
  </div>
  <div class="main">
    <div class="invitation-box">
      <% @groups.each do |group| %>
        <div class="invitation-box" >
          <div class="invitation-box__part">
            <%= group.name %>
          </div>
          <div class="invitation-box__part2">
            <p>Members</p>
            <div class="invitation-box__part2__info">
              <% group.users.each do |user| %>
                <ul>             
                  <%= link_to user_path(user) do %>
                    <li><%= user.name %></li>
                    <li><%= image_tag "#{user.image}", class: "invitation-box__part2__info__image" %></li>
                  <% end %>
                </ul>
              <% end %>
            </div>
          </div>
          <div class="invitation-box__part3">
            <% group.recruitments.each do |recruitment| %>
              <ul>
                <li><%= recruitment.title %></li>
                <li><%= image_tag "#{recruitment.image}", class: "invitation-box__part3__image" %></li>
                <li><%= recruitment.adress %></li>
                <li><%= recruitment.description %></li>
              </ul>
            <% end %>
            <% if group.user_ids.include?( current_user.id ) %>
              <%= link_to "編集", edit_group_path(group), class:"edit-btn" %>
              <%= link_to "削除", group_path(group), method: :delete, class:"edit-btn" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<%= render partial: 'form' %>