config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#top"
  resources :posts, only: [:create, :destroy]
  resources :members, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create, :destroy]
  end
  resources :groups, only: [:index, :new, :edit, :update, :create, :destroy]
  resources :users, only: [:index, :edit, :show, :update] do
    collection do
      get 'search'
    end
  end

  namespace :following do
    resources :followeds, only: [:show] do
      resource :follow_requests, only:[:create, :destroy]
    end
  end
  
  namespace :followed do
    resources :followeds, only: [:show, :edit, :update] do
      resources :follow_okaies, only:[:index, :show, :destroy]
      post '/follow_requests/:id' => 'follow_requests#allow', as: 'allow'
      resources :follow_requests, only:[:index, :show, :destroy]
    end
  end
  get 'home/message'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# Validation
  validates :name, presence: true, uniqueness: true
  validates :work, :adress, presence: true

# Relation
  has_many :posts
  has_many :following_requests, dependent: :destroy, foreign_key: :following_id, class_name: "FollowRequest"
  has_many :followed_requests, dependent: :destroy, foreign_key: :followed_id, class_name: "FollowRequest"
  has_many :following_okays, dependent: :destroy, foreign_key: :following_id, class_name: "FollowOkay"
  has_many :followed_okays, dependent: :destroy, foreign_key: :followed_id, class_name: "FollowOkay"
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :member_users
  has_many :members, through: :member_users
  has_many :messages

  mount_uploader :image, ImageUploader

# Enum
  enum gender: {男性:1, 女性:2}
  enum adress: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

# Method
## 検索
  def self.search(search)
    if search
      User.where('work LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end
## フォローリクエスト判定
  def already_requested?(followed)
    self.following_requests.exists?(followed_id: followed.id)
  end
## 仲間登録済み判定
  def already_following?(following)
    self.followed_okays.exists?(following_id: following.id)
  end

  def already_followed?(followed)
    self.following_okays.exists?(followed_id: followed.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top]
  
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user 
      redirect_to root_path, alert: 'アクセスできません。'
    end
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to user_path(user), notice: "ユーザー情報が更新されました。"
    else
      render :edit
    end
  end

  def search
    @users = User.search(params[:keyword])
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :gender, :adress, :work, :image, :profile, :email)
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.id == user.id %>
  <% if current_user.following?(user) %>
    <%= render 'users/unfollow', user: user %>
  <% else %>
    <%= render 'users/follow', user: user %>
  <% end %>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    フォロー
  </a>
  &nbsp;
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/edit.html.erb
<div class="user-new-area">
  <div class="user-new-box">
      <div class="left-box">
      <h2>編集する</h2>
      <%= form_for @user do |f| %>

        <div class="form-group">
          <%= f.label :"名前*" %><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-part" %>
        </div>  

        <div class="form-group">
          <%= f.label :"年齢" %><br />
          <%= f.text_field :age, autofocus: true, autocomplete: "age", class: "form-part" %>
        </div>  

        <div class="form-group">
          <%= f.label :"性別" %><br />
          <%= f.select :gender, User.genders.keys, {prompt: '選択してください'}, autofocus: true, autocomplete: "gender", class: "form-part" %>
        </div>
        
        <div class="form-group">
          <%= f.label :"仕事・特技*" %><br />
          <%= f.text_field :work, autofocus: true, autocomplete: "work", class: "form-part" %>
        </div> 
        
        <div class="form-group">
          <%= f.label :"イメージ" %><br />
          <%= f.file_field :image, autofocus: true, autocomplete: "image", class: "form-part" %>
        </div>

        <div class="form-group">
          <%= f.label :"住所*" %><br />
          <%= f.select :adress, User.adresses.keys, {prompt: '選択してください'}, autofocus: true, autocomplete: "adress", class: "form-part" %>
        </div>

        <div class="form-group">
          <%= f.label :"メールアドレス*" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-part" %>
        </div>

        <div class="form-group">
          <%= f.label :"自己紹介" %><br />
          <%= f.text_field :profile, autofocus: true, autocomplete: "profile", class: "form-part" %>
        </div>

        <div class="actions">
          <%= f.submit "更新する",class: "user-update" %>
        </div>
      <% end %>

    </div>
    <div class="right-box">
      <%= image_tag 'tori2.jpg', class:"login-img" %> 
    </div>
  </div>
</div>




     

app/views/users/index.html.erb
<header>
  <div class="header-left">
    <% if @user.id == current_user.id %>
      <h1>Creators*</h1>
    <% else %>
      <h1><%= @user.name %>'s page</h1>
    <% end %>
  </div>
  <div class="header-right">
    <ul class="header-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "マイページ", user_path(@user.id) %></li>
    </ul> 
  </div>
</header>

<div class="user-index">
  <div class="side">
    <div class="search-box">
      <%= search_form_for @q do |f| %>
        <div class="search-item">
          <%= f.label :work, "Work: 　" %>
          <%= f.search_field :work_cont, class: "form-part1" %>
        </div>
        <div class="search-item">
          <%= f.label :age, "Age:　　" %>
          <%= f.number_field :age_gteq, class: "form-part" %><br><span>以上〜</span>
          <%= f.number_field :age_lt, class: "form-part" %><br><span>未満</span>
        </div>
        <div class="search-item">
          <%= f.label :adress, "Address:" %>
          <%= f.select :adress_eq, User.adresses.to_a.map{|k, v| [User.adresses_i18n[k], v]}, class: "form-part" %>
        </div>
        <%= f.submit "search", class: "sign-up" %> 
      <% end %>
    </div>
  </div>
  <div class="main">
    <div class="users">
      <% @users.each do |user| %>
        <div class="user-box">
          <div class="user-img">
            <%= link_to user_path(user.id) do %>
              <% if user.image? %>  
                <%= image_tag user.image.url, class: "user-img__item" %>
              <% else %>
                <%= image_tag 'noimage2.png', class: "user-img__item"  %>
              <% end %>
            <% end %>
            <div class="user-info">
              <%= link_to user_path(user.id) do %>
                <p><%= user.name %></p>
                <p><%= user.work %></p>
                <p><%= user.adress %></p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<header>
    <div class="header-left">
      <h1>Creators*</h1>
    </div>
    <div class="header-right">
      <ul class="header-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in?%>
          <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
        <% end %>
      </ul> 
    </div>
</header>

<div class="search-box">
  <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "クリエイターを探す", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
</div>

<div class="users">
  <% @users.each do |user| %>
    <div class="user-box">
      <div class="user-img">
        <%= link_to user_path(user.id) do %>
          <%= image_tag user.image.url, class: "user-img__item" %>
        <% end %>
        <div class="user-info">
          <%= link_to user_path(user.id) do %>
            <p><%= user.name %></p>
            <p><%= user.work %></p>
            <p><%= user.adress %></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<header>
    <div class="header-left">
      <% if @user.id == current_user.id %>
        <h1>Mypage*</h1>
      <% else %>
        <h1><%= @user.name %>'s page</h1>
      <% end %>
    </div>
    <div class="header-right">
      <ul class="header-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if @user.id == current_user.id %>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "プロフィール編集", edit_user_path(@user.id) %><i class="fas fa-edit"></i></li>
          <li><%= link_to "仲間", followed_followed_follow_requests_path(@user.id) %><i class="fas fa-users"></i></li></li>
          <li><%= link_to "メッセージ", home_message_path %> <i class="far fa-comment-alt"></i></li>
        <% else %>
          <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul> 
    </div>
</header>

<div class="profile-box">
  <div class="user-profile">
    <p class="user-profile__name"><%= @user.name %></p>
    <p>age: <%= @user.age %></p>
    <p>gender: <%= @user.gender %></p>
    <p>address: <%= @user.adress %></p>
    <p>speciality: <%= @user.work %></p>
    <p>profile: <%= @user.profile %></p>
    <% if @user.id == current_user.id %>
      <p>emai: <%= @user.email %></p>
    <% end %>
  </div>  
  <div class="user-img">
    <% if @user.image? %>  
      <%= image_tag @user.image.url, class: "user-img__item" %>
    <% else %>
      <%= image_tag 'noimage2.png', class: "user-img__item"  %>
    <% end %>
  </div>
  <% if @user.id != current_user.id %>
    <% if current_user.already_followed?(@user) %>
      <div class="fololowed-btn">
        仲間登録済みです
      </div>
    <% elsif current_user.already_following?(@user) %>
      <div class="fololowed-btn">
        仲間登録済みです
      </div>
    <% elsif current_user.already_requested?(@user) %>
      <%= link_to following_followed_follow_requests_path(followed_id:@user.id), method: :delete do %>
        <div class="fololow-btn1">
          フォローリクエスト取消
        </div>
      <% end %>
    <% else %>
      <%= link_to following_followed_follow_requests_path(followed_id:@user.id), method: :post do %>
        <div class="fololow-btn2">
          フォローリクエスト送信
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="post-index">
  <% if @user.id == current_user.id %>
    <div class="post-form">
      <div class="post-form__title">
        <p>作品を投稿する</p>
      </div>
      <div class="post-form__box">
        <%= form_with(model: [@post], local: true) do |form| %>
          <div class="post-field">
            <%= form.text_field :title, placeholder: "タイトル" ,class: "form-part" %>
          </div>

          <div class="post-field">
            <%= form.file_field :image,class: "form-part1" %>
          </div>

          <div class="post-field"">
            <%= form.submit "投稿",class: "sign-up" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="post-box">
    <% @user.posts.each do |post| %>
      <div class="post">
        <%= image_tag post.image.url, class: "post-image" %>
        <div class="icons">
          <h5><%= post.user.name %></h5>
          <p><%= post.title %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'users/stats' %>
    <h2><%= @title %></h2>
      <% if @users.any? %>
          <% @users.each do |user| %>
          <div class="user_avatars">
            <span><img src="<%= user.avatar.url(:thumb) %>"></span><br />
            <%= link_to user.username ,user_path(user) %>
          </div>
          <% end %>
      <% end %>
    </section>
  </aside>
</div>