config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#top"
  resources :posts, only: [:create, :destroy]
  resources :members, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create, :destroy]
  end
  resources :groups, only: [:index, :new, :edit, :update, :create, :destroy]
  resources :users, only: [:index, :edit, :show, :update] do
    collection do
      get 'search'
    end
  end

  namespace :following do
    resources :followeds, only: [:show] do
      resource :follow_requests, only:[:create, :destroy]
    end
  end
  
  namespace :followed do
    resources :followeds, only: [:show, :edit, :update] do
      resources :follow_okaies, only:[:index, :show, :destroy]
      post '/follow_requests/:id' => 'follow_requests#allow', as: 'allow'
      resources :follow_requests, only:[:index, :show, :destroy]
    end
  end
  get 'home/message'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @user = current_user
  end

  def message
    @user = current_user
    @members = @user.members.order('created_at DESC')
  end

end

app/views/home/message.html.erb
<header>
  <div class="header-left">
    <% if @user.id == current_user.id %>
      <h1>Message*</h1>
    <% else %>
      <h1><%= @user.name %>'s page</h1>
    <% end %>
  </div>
  <div class="header-right">
    <ul class="header-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "マイページ", user_path(@user.id) %></li>
    </ul> 
  </div>
</header>

<body>
  <div class ="message-box" >
    <div class="side">
      <div class= "new-group">
        <%= link_to "Make Member", new_member_path, class:"make-member-btn" %>
      </div>
      <div class="member">
        <% @members.each do |member| %>
          <div class= "member-box">
            <%= link_to member_messages_path(member) do %> 
              <p class="member-name"><%= member.name %></p> 
            <% end %>
            <div class ="member-list">
              <% member.users.each do |user| %>
                <ul>             
                  <li><%= user.name %></li>
                  <li><%= image_tag "#{user.image}", class: "member-image" %></li>
                </ul>
              <% end %>
            </div>
            <% if member.users.count > 5 %>
              <p class="member-count">他{<%= member.users.count-5 %>人}</p>
            <% end %>
            <p class="last-message"><%= member.show_last_message %>
          </div>
         <% end %>
      </div>
    </div>
    <%# <div class="main">
      <div class="main-top">
        <div class="main-top__group">
          <h3 class="main-top__group">メンバーを作ってトークしよう</h3>
        </div>
        <div class="main-top__member">
          <p class="main-top__member__text">Member :</p>
          <ul class="main-top__member__name">
            <li>shi</li>
            <li>shi</li>
            <li>shi</li>
          </ul>
        </div>
      </div>
      <div class="main-message">
        <div class="main-message__box1">
          おはよう。お久しぶりです。お元気でしたでしょうか？
        </div>
        <div class="main-message__box2">
          こんにちは。ご無沙汰しております。
        </div>
      </div>
      <div class="main-bottom"> %>
        <%# <%= form_with model:  [@member, @message], html: {class: "message-form"}, local: true do |f| %>
          <%# <div class ="form-box"> 
            <%= f.text_field :message, class: "form-box__message", placeholder: "type a message" %>
            <%# <%= f.submit %>
          <%# </div>
        <% end %> 
        <%# <form class="message-form"> %>
            <%# <input type="text" >
            <label class="form-box__imag">
              <i class="fas fa-image"></i>
            <input type="file", class="form-box__icon" >
            <input type="submit", class="send-btn", value="Send" > %>
          <%# </div>
        </form> %>
      </div>
    </div>
  </div>
</body>

  <%# .Footer
    = form_with model: [@group, @message], html: {class: "Form"}, local: true do |f|
      .Form__contents
        = f.text_field :content, class: 'Form__inputContent', placeholder: 'type a message'
        = f.label :image, class: 'Form__inputImage' do
          = icon('far', 'image', class: 'Form__icon')
          = f.file_field :image, class: 'Hidden'
      = f.submit 'Send', class: 'Form__submit' %>

app/views/home/top.html.erb
<header>
    <div class="header-left">
      <h1>Create*</h1>
    </div>
    <div class="header-right">
      <ul class="header-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in?%>
          <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
        <% end %>
      </ul> 
    </div>
</header>
  
<div class="home">
  <div class="home-top"> 
  
    <div class="home-menu">
      <p><%= link_to "クリエイターと出会う", users_path %></p>
      <p><%= link_to "仲間を募集する", new_group_path %></p>
      <p><%= link_to "一緒に創りませんか？", groups_path %></p>
    </div>  
    <div class="home-img1">    
      <%= image_tag 'nokos.jpg', class:"home-img1__box" %> 
    </div>  
    <div class="home-img2">    
      <%= image_tag 'flower5.jpg', class:"home-img2__box" %> 
    </div>
    
  </div>
  <div class="color-box">
    <%# <% if user_signed_in?  %>
      <%# <%= @user.name %>
    <%# <% end %>      
  </div>
</div>